### ISSUE TITLE
test_construction failed on Dinkumware

### ISSUE THREAD

**Issue by BinCaoWR** [boostorg/poly_collection#16]
There are a number of tests from test_construction failed on Dinkumware. I see some tests in test_construction.cpp have worked around for BOOST_LIBSTDCXX_VERSION. Any adaptation needed for BOOST_DINKUMWARE_STDLIB?

The Dinkumware version I'm using is 804:
`BOOST_DINKUMWARE_STDLIB=804 [-W#pragma-messages]`
`BOOST_STDLIB="Dinkumware standard library version " "804" [-W#pragma-messages]`

The failed tests as below:
`../libs/poly_collection/test/test_construction.cpp(97): test 'p3.get_allocator().comes_from(root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = false, PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<boost::type_erasure::_self>, std::allocator<boost::type_erasure::any<boost::mpl::vector2<boost::type_erasure::incrementable<boost::type_erasure::_self>, boost::type_erasure::typeid_<boost::type_erasure::_self> >, boost::type_erasure::_self &> > >, ValueFactory = test_utilities::auto_increment, Types = <any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self &>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>>]'
../libs/poly_collection/test/test_construction.cpp(116): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = false, PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<boost::type_erasure::_self>, std::allocator<boost::type_erasure::any<boost::mpl::vector2<boost::type_erasure::incrementable<boost::type_erasure::_self>, boost::type_erasure::typeid_<boost::type_erasure::_self> >, boost::type_erasure::_self &> > >, ValueFactory = test_utilities::auto_increment, Types = <any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self &>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>>]'
../libs/poly_collection/test/test_construction.cpp(116): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<boost::type_erasure::_self>, std::allocator<boost::type_erasure::any<boost::mpl::vector2<boost::type_erasure::incrementable<boost::type_erasure::_self>, boost::type_erasure::typeid_<boost::type_erasure::_self> >, boost::type_erasure::_self &> > >, ValueFactory = test_utilities::auto_increment, Types = <any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self &>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>>]'
../libs/poly_collection/test/test_construction.cpp(143): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<boost::type_erasure::_self>, std::allocator<boost::type_erasure::any<boost::mpl::vector2<boost::type_erasure::incrementable<boost::type_erasure::_self>, boost::type_erasure::typeid_<boost::type_erasure::_self> >, boost::type_erasure::_self &> > >, ValueFactory = test_utilities::auto_increment, Types = <any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self &>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>>]'
../libs/poly_collection/test/test_construction.cpp(179): test 'p2.get_allocator().comes_from(Propagate?root2:root1)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<boost::type_erasure::_self>, std::allocator<boost::type_erasure::any<boost::mpl::vector2<boost::type_erasure::incrementable<boost::type_erasure::_self>, boost::type_erasure::typeid_<boost::type_erasure::_self> >, boost::type_erasure::_self &> > >, ValueFactory = test_utilities::auto_increment, Types = <any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self &>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>>]'
../libs/poly_collection/test/test_construction.cpp(180): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<boost::type_erasure::_self>, std::allocator<boost::type_erasure::any<boost::mpl::vector2<boost::type_erasure::incrementable<boost::type_erasure::_self>, boost::type_erasure::typeid_<boost::type_erasure::_self> >, boost::type_erasure::_self &> > >, ValueFactory = test_utilities::auto_increment, Types = <any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self &>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>>]'
../libs/poly_collection/test/test_construction.cpp(97): test 'p3.get_allocator().comes_from(root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = false, PolyCollection = boost::poly_collection::base_collection<base_types::base, std::allocator<base_types::base> >, ValueFactory = test_utilities::auto_increment, Types = <base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5>]'
../libs/poly_collection/test/test_construction.cpp(116): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = false, PolyCollection = boost::poly_collection::base_collection<base_types::base, std::allocator<base_types::base> >, ValueFactory = test_utilities::auto_increment, Types = <base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5>]'
../libs/poly_collection/test/test_construction.cpp(116): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::base_collection<base_types::base, std::allocator<base_types::base> >, ValueFactory = test_utilities::auto_increment, Types = <base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5>]'
../libs/poly_collection/test/test_construction.cpp(143): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::base_collection<base_types::base, std::allocator<base_types::base> >, ValueFactory = test_utilities::auto_increment, Types = <base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5>]'
../libs/poly_collection/test/test_construction.cpp(179): test 'p2.get_allocator().comes_from(Propagate?root2:root1)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::base_collection<base_types::base, std::allocator<base_types::base> >, ValueFactory = test_utilities::auto_increment, Types = <base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5>]'
../libs/poly_collection/test/test_construction.cpp(180): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::base_collection<base_types::base, std::allocator<base_types::base> >, ValueFactory = test_utilities::auto_increment, Types = <base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5>]'
../libs/poly_collection/test/test_construction.cpp(97): test 'p3.get_allocator().comes_from(root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = false, PolyCollection = boost::poly_collection::function_collection<function_types::int_alias (int), std::allocator<boost::poly_collection::detail::callable_wrapper<function_types::int_alias (int)> > >, ValueFactory = test_utilities::auto_increment, Types = <function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5>]'
../libs/poly_collection/test/test_construction.cpp(116): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = false, PolyCollection = boost::poly_collection::function_collection<function_types::int_alias (int), std::allocator<boost::poly_collection::detail::callable_wrapper<function_types::int_alias (int)> > >, ValueFactory = test_utilities::auto_increment, Types = <function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5>]'
../libs/poly_collection/test/test_construction.cpp(116): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::function_collection<function_types::int_alias (int), std::allocator<boost::poly_collection::detail::callable_wrapper<function_types::int_alias (int)> > >, ValueFactory = test_utilities::auto_increment, Types = <function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5>]'
../libs/poly_collection/test/test_construction.cpp(143): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::function_collection<function_types::int_alias (int), std::allocator<boost::poly_collection::detail::callable_wrapper<function_types::int_alias (int)> > >, ValueFactory = test_utilities::auto_increment, Types = <function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5>]'
../libs/poly_collection/test/test_construction.cpp(179): test 'p2.get_allocator().comes_from(Propagate?root2:root1)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::function_collection<function_types::int_alias (int), std::allocator<boost::poly_collection::detail::callable_wrapper<function_types::int_alias (int)> > >, ValueFactory = test_utilities::auto_increment, Types = <function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5>]'
../libs/poly_collection/test/test_construction.cpp(180): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [Propagate = true, AlwaysEqual = true, PolyCollection = boost::poly_collection::function_collection<function_types::int_alias (int), std::allocator<boost::poly_collection::detail::callable_wrapper<function_types::int_alias (int)> > >, ValueFactory = test_utilities::auto_increment, Types = <function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5>]'
18 errors detected.`

**Comment by joaquintides** [comment]
What compiler are you testing this in? Visual Studio's std library (derived from Dinkumware's) goes only up to `_CPPLIB_VER`  (of which `BOOST_DINKUMWARE_STDLIB` is an alias) = 650, so this 804 value is quite shocking.

Also, looks like you're not using the most recent version of Boost.PolyCollection (there's no possibly failing test located at `test_construction.cpp(97)`). Care to rerun with Boost 1.71.0?

**Comment by BinCaoWR** [comment]
I'm using gcc-8.1.0. I'm using the std library from Dinkumware(not Visual Studio), the version is V8.04x. My testing was run with Boost 1.70.0. I will try to rerun with Boost 1.71.0.

**Comment by joaquintides** [comment]
Have you had the opportunity to rerun with Boost 1.71.0?

**Comment by BinCaoWR** [comment]
Not yet. We have some local changes have to be re-patched to boost 1.71.0.

**Comment by BinCaoWR** [comment]
It is still failed on boost 1.71.0.
`../libs/poly_collection/test/test_construction.cpp(104): test 'p3.get_allocator().comes_from(root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = false; PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<> >; ValueFactory = test_utilities::auto_increment; Types = {any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self&>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>}]'
../libs/poly_collection/test/test_construction.cpp(123): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = false; PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<> >; ValueFactory = test_utilities::auto_increment; Types = {any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self&>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>}]'
../libs/poly_collection/test/test_construction.cpp(123): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<> >; ValueFactory = test_utilities::auto_increment; Types = {any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self&>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>}]'
../libs/poly_collection/test/test_construction.cpp(150): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<> >; ValueFactory = test_utilities::auto_increment; Types = {any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self&>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>}]'
../libs/poly_collection/test/test_construction.cpp(186): test 'p2.get_allocator().comes_from(Propagate?root2:root1)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<> >; ValueFactory = test_utilities::auto_increment; Types = {any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self&>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>}]'
../libs/poly_collection/test/test_construction.cpp(187): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::any_collection<boost::type_erasure::incrementable<> >; ValueFactory = test_utilities::auto_increment; Types = {any_types::incrementable1, double, any_types::incrementable3, int, boost::type_erasure::any<boost::mpl::vector4<boost::type_erasure::copy_constructible<boost::type_erasure::_self>, boost::type_erasure::assignable<boost::type_erasure::_self, const boost::type_erasure::_self&>, boost::type_erasure::incrementable<boost::type_erasure::_self>, any_types::convertible_to_int<boost::type_erasure::_self> >, boost::type_erasure::_self>}]'
../libs/poly_collection/test/test_construction.cpp(104): test 'p3.get_allocator().comes_from(root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = false; PolyCollection = boost::poly_collection::base_collection<base_types::base>; ValueFactory = test_utilities::auto_increment; Types = {base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5}]'
../libs/poly_collection/test/test_construction.cpp(123): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = false; PolyCollection = boost::poly_collection::base_collection<base_types::base>; ValueFactory = test_utilities::auto_increment; Types = {base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5}]'
../libs/poly_collection/test/test_construction.cpp(123): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::base_collection<base_types::base>; ValueFactory = test_utilities::auto_increment; Types = {base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5}]'
../libs/poly_collection/test/test_construction.cpp(150): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::base_collection<base_types::base>; ValueFactory = test_utilities::auto_increment; Types = {base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5}]'
../libs/poly_collection/test/test_construction.cpp(186): test 'p2.get_allocator().comes_from(Propagate?root2:root1)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::base_collection<base_types::base>; ValueFactory = test_utilities::auto_increment; Types = {base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5}]'
../libs/poly_collection/test/test_construction.cpp(187): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::base_collection<base_types::base>; ValueFactory = test_utilities::auto_increment; Types = {base_types::derived1, base_types::derived2, base_types::derived3, base_types::derived4, base_types::derived5}]'
../libs/poly_collection/test/test_construction.cpp(104): test 'p3.get_allocator().comes_from(root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = false; PolyCollection = boost::poly_collection::function_collection<function_types::int_alias(int)>; ValueFactory = test_utilities::auto_increment; Types = {function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5}]'
../libs/poly_collection/test/test_construction.cpp(123): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = false; PolyCollection = boost::poly_collection::function_collection<function_types::int_alias(int)>; ValueFactory = test_utilities::auto_increment; Types = {function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5}]'
../libs/poly_collection/test/test_construction.cpp(123): test 'p2.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::function_collection<function_types::int_alias(int)>; ValueFactory = test_utilities::auto_increment; Types = {function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5}]'
../libs/poly_collection/test/test_construction.cpp(150): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::function_collection<function_types::int_alias(int)>; ValueFactory = test_utilities::auto_increment; Types = {function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5}]'
../libs/poly_collection/test/test_construction.cpp(186): test 'p2.get_allocator().comes_from(Propagate?root2:root1)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::function_collection<function_types::int_alias(int)>; ValueFactory = test_utilities::auto_increment; Types = {function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5}]'
../libs/poly_collection/test/test_construction.cpp(187): test 'p3.get_allocator().comes_from(Propagate?root1:root2)' failed in function 'void test_allocator_aware_construction() [with bool Propagate = true; bool AlwaysEqual = true; PolyCollection = boost::poly_collection::function_collection<function_types::int_alias(int)>; ValueFactory = test_utilities::auto_increment; Types = {function_types::function1, function_types::function2, function_types::function3, function_types::function4, function_types::function5}]'
18 errors detected.`

**Comment by joaquintides** [comment]
Hi, could you check whether e6fa69fa2598087e6b2fdf78c28b6db10dc31735 clears the errors?

**Comment by joaquintides** [comment]
I refined the commit, please use 40cd7e37147a0cc5d1196a0eff9552ee96f1d811 as well.

**Comment by BinCaoWR** [comment]
Thanks for the quick fix. It passed with your changes.

**Comment by joaquintides** [comment]
OK, closing then.

If you don't mind, a year from now I'd like to reach back to you in order to run tests with `BOOST_DETECT_OUTDATED_WORKAROUNDS` to determine if newer versions of Dinkumware stdlib still require the workarounds.

**Comment by BinCaoWR** [comment]
Sure. Thanks again.

**Comment by joaquintides** [comment]
Hi, a year has passed since we closed this and I'd appreciate if you could get me some new info:
* What is the value of `BOOST_DINKUMWARE_STDLIB` in your current environment? (It used to be 804.)
* If this value has changed, would you mind re-running tests with the macro `BOOST_DETECT_OUTDATED_WORKAROUNDS` globally defined? This will tell us if the underlying Dinkumware problem has been fixed.

**Comment by calvincramer** [comment]
Hi there, `BOOST_DINKUMWARE_STDLIB` is still `804`, and `test_construction` passes on all of the architectures we test for.

**Comment by joaquintides** [comment]
OK, so things stay the same. I'll be back in a year to see if something's changed. Thank you!

**Comment by joaquintides** [comment]
Hi, a year has passed and I'd like to ask again to see if things have changed:
* What is the value of `BOOST_DINKUMWARE_STDLIB` in your current environment? (It used to be 804.)
* If this value has changed, would you mind re-running tests with the macro `BOOST_DETECT_OUTDATED_WORKAROUNDS` globally defined? This will tell us if the underlying Dinkumware problem has been fixed.

**Comment by calvincramer** [comment]
@joaquintides `BOOST_DINKUMWARE_STDLIB` is still `804`, so no change.

**Comment by joaquintides** [comment]
Ok, looks like this a pretty stable library. Will ask back in a year if you don't mind.

**Comment by calvincramer** [comment]
Please do!

**Comment by joaquintides** [comment]
Hi, a year has passed and I'd like to ask again to see if things have changed:
* What is the value of `BOOST_DINKUMWARE_STDLIB` in your current environment? (It used to be 804.)
* If this value has changed, would you mind re-running tests with the macro `BOOST_DETECT_OUTDATED_WORKAROUNDS` globally defined? This will tell us if the underlying Dinkumware problem has been fixed.
