### ISSUE TITLE
GCC 9.3 and newer fails to compile segment<base>().begin();

### ISSUE THREAD

**Issue by kjetilj** [boostorg/poly_collection#20]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95888

https://godbolt.org/z/WEj3cr

Bug in GCC, but if a workaround exists that would be great.

**Comment by joaquintides** [comment]
Worked around for GCC 9.3-10 as per out private conversation. Leaving this open till we get confirmation that the bug is fixed in GCC 11.

**Comment by joaquintides** [comment]
GCC bug fixed in 10.3.0. Closing issue, thanks for reporting.
